### ISSUE TITLE
启动成功收不到邮件消息

### ISSUE THREAD

**Issue by tulies** [sunzsh/mail_to_gitlab_issues#1]
请问    mail_domain: 'your_mail_domain',。 这个是维护smtp.xxx.com ，还是维护xxx.com

**Comment by sunzsh** [comment]
如果MX记录配置的是`@.xxx.com`，那么mail_domain就应该配置xxx.com

**Comment by tulies** [comment]
> 如果MX记录配置的是`@.xxx.com`，那么mail_domain就应该配置xxx.com

嘿嘿 谢谢老哥回答 有空我再看下。有问题再请教
