### ISSUE TITLE
你好，我想知道怎么在本地去进行调试

### ISSUE THREAD

**Issue by wangshiz** [sunzsh/mail_to_gitlab_issues#3]
你好，我是从抖音平台看到你的视频，但我这边需要修改一些代码来迎合我这边的需求，所以我想知道我应该怎么在本地去进行调试你这个项目，谢谢

**Comment by sunzsh** [comment]
可以在在你想调试的时候 利用内网穿透的软件（例如frp）将 服务器收到的邮件报文 转发到你自己的电脑上
